
##  CONFIG
results: "results/2024_0624_initial_test"
methodsTable: "config/config_methods_example.tsv"
methods: [ENCODE_rE2Gext, ABC_full]
biosampleGroups: # will be computed for any predictors with all biosamples represented (in addition to ALL; must be distinct from biosample names)
  Blood: [K562, GM12878]

comparisonsTable: "config/config_comparisons_example.tsv" # additional comparisons to compute and plot; columns: name, biosamples[groups], traits

## REFERENCE / RESOURCES /  PARAMS
baseDir: "/oak/stanford/groups/engreitz/Users/sheth/GWAS_benchmarking_working/GWAS_E2G_benchmarking"
scratchDir: "/scratch/users/shethm"
thresholdPIP: 0.1
thresholdPval: 0.05
numPoPSGenes: 2 # for evaluating gene-linking
numPredGenes: 2 # for evaluating gene-linking

# Variant files
variantKey: "resources/UKBB_variant_key.tsv" # columns: trait, variant_file
credibleSets: "resources/UKBiobank.ABCGene.anyabc.tsv"
bgVariants: "/oak/stanford/groups/engreitz/Users/sheth/hg38_resources/backgroundSNPs/all.bg.SNPs.hg38.baseline.v1.1.bed.sorted" # 10M common variants

# Genome annotation
chrSizes: "/oak/stanford/groups/engreitz/Users/sheth/eQTLEnrichment-integrated/eQTLEnrichment/resources/genome_annotation/GRCh38_EBV.chrom.sizes.tsv" 
partition: "/oak/stanford/groups/engreitz/Users/sheth/eQTLEnrichment-integrated/eQTLEnrichment/resources/genome_annotation/PartitionCombined.bed" # distal noncoding regions: ABC,AllPeaks,Other,OtherIntron
TSS: "/oak/stanford/groups/engreitz/Users/sheth/eQTLEnrichment-integrated/eQTLEnrichment/resources/genome_annotation/CollapsedGeneBounds.hg38.TSS500bp.bed" # is this ever used?
genes: "/oak/stanford/groups/engreitz/Users/sheth/eQTLEnrichment-integrated/eQTLEnrichment/resources/genome_annotation/CollapsedGeneBounds.hg38.bed"







