
##  CONFIG
results: "results/2025-0429_segment_curatedGWAS" # output directory for results
methodsTable: "config/config_methods_FLINC.tsv"
predictionsTable: "config/config_predictions_FLINC.tsv" # file paths for predictions; column for biosample and each method
methods: [scE2G_multiome]
comparisonsTable: "config/config_comparisons_FLINC.tsv" # comparisons to compute and plot; columns: name, biosample[group], trait[group]

# groups of biosamples and traits to combine
biosampleGroups: # will be computed for any predictors with all biosamples represented (in addition to ALL; must be distinct from biosample names)
    IMMUNE: [B_cells, Circulating_NK]

traitGroups: # for benchmarking against groups of traits with potentially shared variants, in addition to ALL; must be distinct from trait names
  WHR_traits: [WHR_Pulit2019, WHR_BMIadj_Women_Christakoudi2021]

## REFERENCE / RESOURCES /  PARAMS
baseDir: "/projects/hh_liver_cohorts-AUDIT/people/wkq953/scE2G/GWAS_E2G_benchmarking"
scratchDir: "/projects/hh_liver_cohorts-AUDIT/people/wkq953/scE2G"
nThresholdSteps: 25 # for enrichment-recall curves
thresholdPIP: 0.1
thresholdPval: 0.05
numPoPSGenes: 2 # for evaluating gene-linking
numPredGenes: 2 # for evaluating gene-linking
plotFixedScale: False # if true, heatmaps will be plotted with the same color scale across all predictors

# Variant files
variantKey: "resources/SEGMENT_GWAS_variant_key.tsv" # columns: trait, variant_file
genePrioritizationTable: "resources/UKBiobank.ABCGene.anyabc.tsv" # minimal columns: CredibleSet, Disease, TargetGene, truth, POPS.Score, PromoterDistanceToBestSNP
bgVariants: "/maps/projects/hansen-AUDIT/people/wkq953/resources/eQTL_benchmark_resource/all.bg.SNPs.hg38.baseline.v1.1.bed.sorted" # 10M common variants, 9991229 in total

# Genome annotation
chrSizes: "resources/genome_annotation/GRCh38_main.chrom.sizes.tsv" 
partition: "resources/genome_annotation/PartitionCombined.bed" # distal noncoding regions: ABC,AllPeaks,Other,OtherIntron
TSS: "resources/genome_annotation/CollapsedGeneBound.hg38.intGENCODEv43.TSS500bp.bed" 
